---
title: "Meta_analysis"
output: html_document
date: "2024-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,     # Suppress warnings from R code
  message = FALSE     
)
```

## STEPNIAK DATA
```{r, message=FALSE}
library(mixOmics)

data_stepniak <- read.table("../../Glioma/Stepniak/RNAseq/nextflow/star_salmon/salmon.merged.gene_counts.tsv", header = TRUE)
#--> Phenotypic matrix 
pdata_stepniak <- read.csv("pdata_DA_complete.csv", sep =";", header = TRUE)
#pdata <- pdata[-6,]
row.names(pdata_stepniak) <- pdata_stepniak$Sample

#--> Count matrix
mrna_raw_counts_stepniak <- read.table("../../Glioma/Stepniak/RNAseq/nextflow/star_salmon/salmon.merged.gene_counts.tsv", header = TRUE)
row.names(mrna_raw_counts_stepniak) <- mrna_raw_counts_stepniak$gene_id
mrna_raw_counts_stepniak <- mrna_raw_counts_stepniak[,-c(1:2)]
mrna_raw_counts_stepniak <- mrna_raw_counts_stepniak[,c(1,4,3,6,5,7)]

#--> Order and match
mrna_raw_counts_stepniak <- mrna_raw_counts_stepniak[,match(pdata_stepniak$Sample, colnames(mrna_raw_counts_stepniak), nomatch = 0)]
pdata_stepniak <- pdata_stepniak[pdata_stepniak$Sample %in% colnames(mrna_raw_counts_stepniak),]

#--> Filter lowly expressed genes
library(HTSFilter)

mrna_filter_stepniak <- HTSFilter(round(mrna_raw_counts_stepniak),
                         pdata_stepniak$Group,
                         s.min=1, s.max=200)

mrna_filter_stepniak <- mrna_filter_stepniak$filteredData

#--> Feature annotation
mrna_gene_stepniak <- read.table("../../Glioma/Stepniak/RNAseq/nextflow/star_salmon/salmon.merged.gene_counts.tsv", header = TRUE)[,c(1:2)]
# --> Transpose the df to have the sample in lines
t_mrna_filter_stepniak <- as.data.frame(t(mrna_filter_stepniak))

```
## JIGNA DATA
```{r, message=FALSE}
data_jigna <- mrna_raw_counts <- read.table("salmon.merged.gene_counts_Jigna.tsv", header = TRUE)
#--> Phenotypic matrix 
pdata_jigna <- read.csv("pdata_Jigna.csv", sep =";", header = TRUE)
#pdata <- pdata[-6,]
row.names(pdata_jigna) <- pdata_jigna$Sample

#--> Count matrix
mrna_raw_counts_jigna <- read.table("salmon.merged.gene_counts_Jigna.tsv", header = TRUE)
row.names(mrna_raw_counts_jigna) <- mrna_raw_counts_jigna$gene_id
mrna_raw_counts_jigna <- mrna_raw_counts_jigna[,-c(1:2)]
mrna_raw_counts_jigna <- mrna_raw_counts_jigna[,c(1,3,5,7,9,11,13,15)]

#--> Order and match
mrna_raw_counts_jigna <- mrna_raw_counts_jigna[,match(pdata_jigna$Sample, colnames(mrna_raw_counts_jigna), nomatch = 0)]
pdata_jigna <- pdata_jigna[pdata_jigna$Sample %in% colnames(mrna_raw_counts_jigna),]

#--> Filter lowly expressed genes
library(HTSFilter)

mrna_filter_jigna <- HTSFilter(round(mrna_raw_counts_jigna),
                         pdata_jigna$Group,
                         s.min=1, s.max=200)

mrna_filter_jigna <- mrna_filter_jigna$filteredData

#--> Feature annotation
mrna_gene_jigna <- read.table("salmon.merged.gene_counts_Jigna.tsv", header = TRUE)[,c(1:2)]
# --> Transpose the df to have the sample in lines
t_mrna_filter_jigna <- as.data.frame(t(mrna_filter_jigna))
#######################################################################################################################

```
## COMBIBNE THE 2 DATAFRAMES
```{r, message=FALSE}

common_cols <- intersect(colnames(t_mrna_filter_jigna), colnames(t_mrna_filter_stepniak))

t_mrna_filter_jigna_common <- t_mrna_filter_jigna[, common_cols]
t_mrna_filter_stepniak_common <- t_mrna_filter_stepniak[, common_cols]
  
X_combined_count_mrna <- rbind(t_mrna_filter_jigna_common,t_mrna_filter_stepniak_common)
Y_pdata <- read.csv("pdata.csv", sep =";", header = TRUE)

class <- as.factor(Y_pdata$Group)
study <- factor(Y_pdata$Study)
```
## MINT sPLS-DA Model
```{r, message=FALSE}

result <- mint.splsda(X = X_combined_count_mrna, Y = class, study = study, ncomp = 3)
plotIndiv(result, comp = c(1, 2), legend = TRUE)
```
## TUNING THE NUMBER OF COMPONENTS
```{r, message=FALSE}

splsda_perf <- perf(result)
plot(splsda_perf)
splsda_perf$predict

optim_ncomp <- 2
```
## TUNING THE NUMBER OF FEATURES
```{r, message=FALSE}

splsda_tune <- tune(X = X_combined_count_mrna, 
                    Y = class, 
                    study = study, 
                    ncomp = optim_ncomp,
                    test.keepX = seq(1, 100, 1),
                    nrepeat = 5,
                    method = "mint.splsda",
                    measure = "BER",
                    dist = "centroids.dist",
                    )

plot(splsda_tune, sd = FALSE)

optim_keepX <- splsda_tune$choice.keepX # extract optimal values

optim_keepX
```
## FINAL MODEL
```{r, message=FALSE}

final_splsda_model <- mint.splsda(X = X_combined_count_mrna, 
                                  Y = class, 
                                  study = study, 
                                  ncomp = optim_ncomp, 
                                  keepX = optim_keepX)
```

```{r, message=FALSE}
cim(final_splsda_model, comp = 2, margins=c(10,5), 
    row.sideColors = color.mixo(as.numeric(class)), 
    row.names = FALSE, title = "MINT sPLS-DA, component 2")


selected_gene_comp2 <- selectVar(final_splsda_model, comp = 2)$name

gene_names <- mrna_gene_stepniak[match(
  selected_gene_comp2, 
  mrna_gene_stepniak$gene_id),]

```
